# Generated by Django 4.1.7 on 2023-04-21 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together={("product", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("product", "user")},
        ),
        migrations.CreateModel(
            name="SuggestedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("price", models.FloatField()),
                ("link", models.URLField()),
                ("image_url", models.URLField()),
                ("category", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
